spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      username: jonggae
      password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    your:
      package:
        name: DEBUG
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  invitation:
    link:
      base-url: https://testdomain.com/invitation/